name: CI (4.x)
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 8
          - os: ubuntu-latest
            jdk: 17
          - os: windows-latest
            jdk: 8
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      deploy: ${{ matrix.jdk == '8' && matrix.os == 'ubuntu-latest' }}
    secrets: inherit
