name: CI (5.x)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'
jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 8
          - os: ubuntu-latest
            jdk: 17
          - os: windows-latest
            jdk: 8
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
    secrets: inherit
